trigger:
 branches:
   include:
     - main

pool:maneesh3456

stages:
  - stage: stage1
    displayName:  install_init_fmt_validate  
    jobs:
      - job: terraforminstall_terrraforminit
        displayName: terraform_install_init
        steps:
         - task: TerraformInstaller@1
           inputs:
             terraformVersion: 'latest'