trigger:
  branches:
    include:
      - main

pool:
  name: Agent_Maneesh

# #  install_init_fmt_validate
stages:
- stage: stage1
  displayName: install_init_fmt_validate
  jobs:
  - job: terraform_install_init
    displayName: terraform_install_init
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Envoirnment/Dev'
        backendServiceArm: 'maneeshNewSPDEC25'
        backendAzureRmResourceGroupName: 'maneesh22'
        backendAzureRmStorageAccountName: 'maneeshstorage01'
        backendAzureRmContainerName: 'maneeshcontainer'
        backendAzureRmKey: 'maneesh.tfstate'

  - job: terraformfmt_terrraformvalidate
    displayName: terraform fmt and validate
    dependsOn: terraform_install_init
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Envoirnment/Dev'
        backendServiceArm: 'maneeshNewSPDEC25'
        backendAzureRmResourceGroupName: 'maneesh22'
        backendAzureRmStorageAccountName: 'maneeshstorage01'
        backendAzureRmContainerName: 'maneeshcontainer'
        backendAzureRmKey: 'maneesh.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'custom'
        commandOptions: 'fmt'
        outputTo: 'console'
        environmentServiceNameAzureRM: 'maneeshNewSPDEC25'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Envoirnment/Dev'

# scanning

- stage: stage2
  displayName: security_scanning
  # dependsOn: stage1
  jobs:
    - job: terraform_scanning
      displayName: scanning
      steps:
        - task: tfsec@1
          displayName: tfsec_scanning
          inputs:
            version: 'v1.26.0'
            workingDirectory: '$(System.DefaultWorkingDirectory)'
      

- stage: stage3
  displayName: terraform_plan
  # dependsOn: stage2
  jobs:
    - job: terraform_plan
      displayName: terraform_init_and_plan
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/Envoirnment/Dev'
          backendServiceArm: 'maneeshNewSPDEC25'
          backendAzureRmResourceGroupName: 'maneesh22'
          backendAzureRmStorageAccountName: 'maneeshstorage01'
          backendAzureRmContainerName: 'maneeshcontainer'
          backendAzureRmKey: 'maneesh.tfstate'
      
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
          environmentServiceNameAzureRM: 'maneeshNewSPDEC25'

  